// @title Mend API
// @version 1.0
// @description AI-powered couples therapy backend API
// @host mend-backend-j0qd.onrender.com
// @BasePath /api

package main

import (
	"os"

	"github.com/gofiber/adaptor/v2"
	"github.com/gofiber/fiber/v2"
	httpSwagger "github.com/swaggo/http-swagger"

	"mend/config"
	"mend/database"
	"mend/routes"

	_ "mend/docs" // Swagger docs generated by swag init
)

func main() {
	// Load env
	config.LoadEnv()

	// Connect DB
	database.ConnectDB()

	// Init app
	app := fiber.New()

	// ✅ This is the only correct way to serve Swagger UI in Fiber
	app.Get("/swagger/*", adaptor.HTTPHandler(httpSwagger.WrapHandler))

	// Register routes
	routes.SetupRoutes(app)

	// Listen
	port := os.Getenv("PORT")
	if port == "" {
		port = "5000"
	}
	app.Listen(":" + port)
}
