# .github/workflows/go.yml

name: Go Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Build backend
        run: go build -o main .

      - name: Run Tests
        run: go test -v ./...

      - name: Upload built binary (optional)
        uses: actions/upload-artifact@v4
        with:
          name: mend-backend
          path: main
